# ENVIRA PDF layout pipeline workflow

Package-backed successor to `../pdf_layoutparser_vF.ipynb`. The reference notebook remains unchanged. This notebook is the orchestrator and preserves end-to-end visual inspection.

## 0. Optional environment installation
Run this once in a fresh Colab runtime; server environments should install dependencies beforehand.

In [1]:
from getpass import getpass
from pathlib import Path
import os
import shutil
import subprocess

GITHUB_USER = "dsdengrasa08"
REPO_NAME = "ENVIRA-Phase-1-Data"
WORKSPACE_DIR = Path("/content/colab_repos")
REPO_DIR = WORKSPACE_DIR / REPO_NAME

os.chdir("/content")
WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)

print(f"Workspace folder: {WORKSPACE_DIR}")
print(f"Target repo path: {REPO_DIR}")

# For private repos, use a GitHub token with read access.
token = getpass("Paste GitHub token: ")
repo_url = f"https://{GITHUB_USER}:{token}@github.com/{GITHUB_USER}/{REPO_NAME}.git"

if REPO_DIR.exists():
    shutil.rmtree(REPO_DIR)

result = subprocess.run(
    ["git", "clone", repo_url, str(REPO_DIR)],
    cwd="/content",
    text=True,
    capture_output=True,
)

# Clear secrets from variables after clone attempt.
token = None
repo_url = None

if result.returncode != 0:
    print("Git clone failed.")
    print(result.stderr)
    raise RuntimeError("Repository was not cloned.")

print(f"Repo cloned successfully to: {REPO_DIR}")

Workspace folder: /content/colab_repos
Target repo path: /content/colab_repos/ENVIRA-Phase-1-Data
Paste GitHub token: ··········
Repo cloned successfully to: /content/colab_repos/ENVIRA-Phase-1-Data

In [2]:
%pip -q install -r /content/colab_repos/ENVIRA-Phase-1-Data/pdf_layout_pipeline/requirements.txt

## 1. Imports and current run configuration

In [3]:
from pathlib import Path
import sys

# Colab leaves the working directory at /content after cloning, while local
# Jupyter sessions may start at either the repository or pipeline directory.
repo_dir = Path(globals().get("REPO_DIR", Path.cwd())).resolve()
project_candidates = (
    repo_dir / "pdf_layout_pipeline",
    Path.cwd() / "pdf_layout_pipeline",
    Path.cwd(),
)
PROJECT_DIR = next(
    (path for path in project_candidates if (path / "src" / "envira_pdf_layout").is_dir()),
    None,
)
if PROJECT_DIR is None:
    raise FileNotFoundError(
        "Could not locate pdf_layout_pipeline/src/envira_pdf_layout. "
        "Run the repository clone cell first or start Jupyter from the repository."
    )
sys.path.insert(0, str(PROJECT_DIR / "src"))
from IPython.display import display
from envira_pdf_layout.config import PipelineConfig
from envira_pdf_layout.runtime import prepare_runtime
from envira_pdf_layout.paths import prepare_document_context
from envira_pdf_layout.model_artifacts import ensure_model_artifacts
from envira_pdf_layout.pdf_io import prepare_pages
from envira_pdf_layout.docling_backend import DoclingBackend
from envira_pdf_layout.pipeline import run_layout_pipeline
from envira_pdf_layout.results import (page_records_dataframe, raw_label_counts_dataframe, summary_dataframe, regions_dataframe, region_type_counts_dataframe, formula_candidates_dataframe)
from envira_pdf_layout.visualization import render_layout_overlays
from envira_pdf_layout.diagnostics import (page1_diagnostics, header_diagnostics, figure_completion_diagnostics, footer_diagnostics, tail_diagnostics, reading_order_diagnostics, stage_exclusions)
from envira_pdf_layout.export import export_pipeline_result

SOURCE_PDF = Path("/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/1-s2.0-S0167880921000803-main.pdf")
PAGE_START = 1
PAGE_END = None
RUN_ID = ""

In [4]:
config = PipelineConfig.from_env(source_pdf=SOURCE_PDF, page_start=PAGE_START, page_end=PAGE_END, run_id=RUN_ID)
config

PipelineConfig(runtime=RuntimeConfig(use_google_drive=True, drive_mount_point=PosixPath('/content/drive'), project_dir=PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling'), offline=False, skip_pip_install=False), document=DocumentConfig(source_pdf=PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/1-s2.0-S0167880921000803-main.pdf'), page_start=1, page_end=None, render_dpi=180, run_id='', prefer_persistent_copy=True), docling=DoclingConfig(artifacts_dir=PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models'), use_local_artifacts=True, require_saved_models=True, auto_download_models=False, force_redownload_models=False, min_model_size_mb=100.0, do_ocr=False, do_table_structure=True, do_formula_enrichment=True, do_code_enrichment=False, code_formula_preset='codeformulav2'), page1=Page1FilterConfig(enabled=True, abstract_aliases=('Abstract', 'Summary'), recover_abstract_heading=True, title_y_min=0.15, title_y_max=0.42, body_anchor_y_max=0.7, lower_metadata_min_y=0.68, hard_footer_y=0.92), headers=HeaderFilterConfig(enabled=True, top_band_ratio=0.14, min_repeat_pages=2), figures=FigureFilterConfig(complete_caption_anchored=True, require_multipanel_hint=True, filter_small_edge_figures=True, header_y1_max=0.12, footer_y0_min=0.9), footer=FooterFilterConfig(enabled=True, compact_enabled=True, min_repeat_pages=2, y0_min=0.88), tail=TailFilterConfig(enabled=True, direct_backmatter_fallback=True), reading_order=ReadingOrderConfig(column_gap_ratio=0.04, min_column_width_ratio=0.2), export=ExportConfig(write_raw=True, write_regions=True, write_overlays=True), exclude_labels=frozenset())

## 2. Runtime and persistent model artifacts

In [5]:
runtime_report = prepare_runtime(config.runtime)
model_report = ensure_model_artifacts(config.docling)
display(runtime_report)
display(model_report)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

{'in_colab': True,
 'project_dir': PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling'),
 'hf_cache': PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/cache/huggingface'),
 'pip_cache': PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/cache/pip'),
 'torch_cache': PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/cache/torch')}

{'artifact_path': PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models'),
 'size_mb': 1246.1519479751587,
 'ready': True,
 'preview': [PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/.docling_models_ready.json'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--docling-layout-heron/preprocessor_config.json'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--docling-layout-heron/config.json'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--docling-layout-heron/model.safetensors'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--docling-models/config.json'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--DocumentFigureClassifier-v2.5/config.json'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--DocumentFigureClassifier-v2.5/preprocessor_config.json'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--DocumentFigureClassifier-v2.5/model.onnx'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--DocumentFigureClassifier-v2.5/model.safetensors'),
  PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models/docling-project--CodeFormulaV2/generation_config.json')]}

## 3. Input preparation and rendered-page inspection

In [6]:
document = prepare_document_context(config)
page_set = prepare_pages(document, config.document.render_dpi)
display(page_records_dataframe(page_set))

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

,page_number,page_pdf_path,page_image_path,width_px,height_px,width_pt,height_pt
0,1,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
1,2,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
2,3,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
3,4,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
4,5,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
5,6,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
6,7,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989
7,8,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1489,1985,595.276001,793.700989

## 4. Initialize Docling once and convert the selected document range

In [7]:
backend = DoclingBackend.from_config(config.docling, model_report["artifact_path"])
conversion = backend.convert(document.pdf_path, (document.page_start, document.page_end))
print("Docling status:", getattr(conversion.result, "status", "unknown"))

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

[transformers] Model config: pad_token_id must be `None` or an integer within the vocabulary (between 0 and 31999), got 128002. This may result in unexpected behavior.

Loading weights:   0%|          | 0/471 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie model.text_model.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
W0811 13:15:38.603000 2221 torch/_inductor/utils.py:1731] [2/0_1] Not enough SMs to use max_autotune_gemm mode
[transformers] Passing `generation_config` together with generation-related arguments=({'do_sample', 'max_new_tokens', 'use_cache'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.

Docling status: ConversionStatus.SUCCESS

## 5. Layout conversion and post-processing
The orchestrator preserves the order-sensitive page-1, header, figure, nested-asset, side-margin, footer, document-tail, post-body asset, and reading-order stages.

In [8]:
run = run_layout_pipeline(conversion, page_set, config)
print("Raw regions:", len(run.raw_regions), "Final main-body regions:", len(run.final_regions))
display(raw_label_counts_dataframe(run.raw_regions))
display(summary_dataframe(run))

Raw regions: 196 Final main-body regions: 91

    docling_label  count
0       list_item     81
1            text     47
2  section_header     26
3     page_footer     10
4         picture      9
5     page_header      8
6         caption      7
7        footnote      3
8           table      3
9         formula      2

,doc_id,page_number,layout_regions,post_body_asset_regions,figure_regions,table_regions,formula_regions,excluded_regions,page_image_path
0,1-s2.0-S0167880921000803-main__abdb34c0bb6a,1,9,0,2,0,0,16,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
1,1-s2.0-S0167880921000803-main__abdb34c0bb6a,2,15,0,0,1,0,1,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
2,1-s2.0-S0167880921000803-main__abdb34c0bb6a,3,15,0,1,0,2,1,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
3,1-s2.0-S0167880921000803-main__abdb34c0bb6a,4,15,0,2,0,0,1,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
4,1-s2.0-S0167880921000803-main__abdb34c0bb6a,5,18,0,1,2,0,1,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
5,1-s2.0-S0167880921000803-main__abdb34c0bb6a,6,13,0,0,0,0,1,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
6,1-s2.0-S0167880921000803-main__abdb34c0bb6a,7,6,0,0,0,0,51,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
7,1-s2.0-S0167880921000803-main__abdb34c0bb6a,8,0,0,0,0,0,33,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...

## 6. Visual layout overlays
These are returned by the visualization module and explicitly displayed here. Asset labels beginning with `A` remain visible alongside main-body reading-order labels.

In [9]:
overlays = render_layout_overlays(run, save=True)
for overlay in overlays[:20]:
    print("Overlay:", overlay.path)
    display(overlay.image)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0001_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0002_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0003_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0004_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0005_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0006_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0007_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

Overlay: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/overlays/page_0008_docling_layout_overlay.png

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

## 7. Region, count, and formula inspection

In [10]:
regions_df = regions_dataframe(run)
inspection_columns = [c for c in ["page_number", "docling_reading_order", "visual_overlay_order", "layout_reading_order", "reading_order_column", "type", "docling_label", "text", "orig", "bbox_px", "width_px", "height_px", "area_px", "page_image_path"] if c in regions_df.columns]
display(regions_df[inspection_columns].head(150))
display(region_type_counts_dataframe(run))
display(formula_candidates_dataframe(run)[inspection_columns].head(50))

,page_number,docling_reading_order,visual_overlay_order,layout_reading_order,reading_order_column,type,docling_label,text,orig,bbox_px,width_px,height_px,area_px,page_image_path
0,1,179,1,1,left,Figure,picture,,None,"[483.15514334029507, 524.0544891357423, 513.82...",30.673600,25.026512,767.653233,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
1,1,6,2,2,left,Text,text,"Naoya Takeda a , Johannes Friedl a, *, David R...","Naoya Takeda a , Johannes Friedl a, *, David R...","[94.01964552272214, 524.2617011522029, 1201.93...",1107.919467,62.994047,69792.331282,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
2,1,10,3,3,left,Text,text,Keywords: Nitrous oxide Sugarcane N fertiliser...,Keywords: Nitrous oxide Sugarcane N fertiliser...,"[94.01964552272214, 761.4661596118967, 208.125...",114.106202,143.226101,16342.986370,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
3,1,11,4,4,left,Section-header,section_header,1. Introduction,1. Introduction,"[94.01964552272214, 1291.0538257109918, 250.56...",156.546192,18.284221,2862.325149,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
4,1,12,5,5,left,Text,text,Nitrous oxide (N2O) is a long-lived atmo...,Nitrous oxide (N2O) is a long-lived atmo...,"[94.02141758670298, 1343.371331554502, 727.971...",633.950239,279.880599,177430.372376,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,7,90,2,2,left,Text,text,This study was funded by Sugar Research ...,This study was funded by Sugar Research ...,"[94.01964552272214, 191.07989190560014, 727.98...",633.963833,149.150740,94556.174884,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
87,7,116,3,3,right,List,list_item,intensively managed pastures in subtropical Au...,intensively managed pastures in subtropical Au...,"[796.8239534869567, 138.7670508187833, 1364.82...",567.996804,34.618157,19663.002379,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
88,7,117,4,4,right,List,list_item,"Friedl, J., Scheer, C., Rowlings, D.W., Delted...","Friedl, J., Scheer, C., Rowlings, D.W., Delted...","[766.9031119447302, 178.60751965424782, 1394.6...",627.717279,74.438630,46726.414392,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
89,7,118,5,5,right,List,list_item,"Giles, M., Morley, N., Baggs, E.M., Daniell, T...","Giles, M., Morley, N., Baggs, E.M., Daniell, T...","[766.9063975570625, 258.4103791895433, 1391.84...",624.937468,54.467433,34038.739391,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
90,7,119,6,6,right,List,list_item,"Grace, P., Shcherbak, I., Macdonald, B., Schee...","Grace, P., Shcherbak, I., Macdonald, B., Schee...","[766.9063975570625, 318.101718408546, 1394.674...",627.768314,54.609350,34282.019415,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...

    page_number            type  count
0             1          Figure      2
1             1  Section-header      1
2             1            Text      6
3             2     Page-footer      1
4             2  Section-header      5
5             2           Table      1
6             2            Text      8
7             3         Caption      1
8             3          Figure      1
9             3         Formula      2
10            3     Page-footer      1
11            3  Section-header      3
12            3            Text      7
13            4         Caption      2
14            4          Figure      2
15            4     Page-footer      1
16            4  Section-header      4
17            4            Text      6
18            5         Caption      4
19            5          Figure      1
20            5     Page-footer      1
21            5  Section-header      3
22            5           Table      2
23            5            Text      7
24            6     Page-footer      1
25            6  Section-header      3
26            6            Text      9
27            7            List      4
28            7  Section-header      1
29            7            Text      1

,page_number,docling_reading_order,visual_overlay_order,layout_reading_order,reading_order_column,type,docling_label,text,orig,bbox_px,width_px,height_px,area_px,page_image_path
34,3,43,11,11,right,Formula,formula,\text {mes and} \\ \text {primeime of} \quad \...,EF ( % ) = N 2 Of N 2 O 0 N Nf × 100 (1),"[766.9053957871121, 981.1857874863158, 1406.63...",639.733423,46.037581,29451.779196,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...
36,3,45,13,13,right,Formula,formula,\begin{array} { c c c c c c c c c c c c c c c ...,"N 2 O ∼ Gamma ( μ , θ ) g ( μi ) = β 0 + te ( ...","[770.3105506741977, 1672.0476863489896, 1400.7...",630.487418,45.670714,28794.810858,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...

## 8. Optional stage diagnostics
Run the relevant display calls while tuning. Diagnostics are produced during processing and displayed here without rerunning detectors.

In [11]:
display(page1_diagnostics(run))
display(header_diagnostics(run))
display(figure_completion_diagnostics(run))
display(footer_diagnostics(run))
display(tail_diagnostics(run))
display(reading_order_diagnostics(run, page_number=document.page_start))

,title,body_anchor,candidate_count,drop_count,protected_article_region_ids
0,"{'layout_region_id': 'p0001_r00006_1', 'page_n...","{'layout_region_id': 'p0001_r00010_1', 'page_n...",4,16,[p0001_r00010_1]

,candidate_count,repeated_signatures,drop_count
0,21,[agriculture ecosystems and environment # # # ...,7

,caption_id,figure_id,multipanel_hint,completed,reason
0,p0003_r00035_1,p0003_r00183_1,False,False,insufficient_multipanel_caption_evidence
1,p0004_r00052_1,p0004_r00184_1,True,False,geometry_preserved_without_image_evidence
2,p0004_r00059_1,p0004_r00185_1,False,False,insufficient_multipanel_caption_evidence
3,p0005_r00063_1,p0005_r00186_1,False,False,insufficient_multipanel_caption_evidence

  repeated_signatures  drop_count
0                  []           0

,boundary_method,conclusion_anchor,boundary,drop_count
0,direct_backmatter_fallback,None,"{'layout_region_id': 'p0007_r00091_1', 'page_n...",82

,layout_region_id,page_number,docling_reading_order,docling_label,type,text,orig,bbox_px,width_px,height_px,area_px,page_image_path,layout_reading_order,visual_overlay_order,included_in_layout_reading_order,reading_order_column,reading_order_band,reading_order_role,reading_order_excluded_reason
0,p0001_r00179_1,1,179,picture,Figure,,None,"[483.15514334029507, 524.0544891357423, 513.82...",30.673600,25.026512,767.653233,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,1,1,True,left,body,article,None
1,p0001_r00006_1,1,6,text,Text,"Naoya Takeda a , Johannes Friedl a, *, David R...","Naoya Takeda a , Johannes Friedl a, *, David R...","[94.01964552272214, 524.2617011522029, 1201.93...",1107.919467,62.994047,69792.331282,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,2,2,True,left,body,article,None
2,p0001_r00010_1,1,10,text,Text,Keywords: Nitrous oxide Sugarcane N fertiliser...,Keywords: Nitrous oxide Sugarcane N fertiliser...,"[94.01964552272214, 761.4661596118967, 208.125...",114.106202,143.226101,16342.986370,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,3,3,True,left,body,article,None
3,p0001_r00011_1,1,11,section_header,Section-header,1. Introduction,1. Introduction,"[94.01964552272214, 1291.0538257109918, 250.56...",156.546192,18.284221,2862.325149,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,4,4,True,left,body,article,None
4,p0001_r00012_1,1,12,text,Text,Nitrous oxide (N2O) is a long-lived atmo...,Nitrous oxide (N2O) is a long-lived atmo...,"[94.02141758670298, 1343.371331554502, 727.971...",633.950239,279.880599,177430.372376,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,5,5,True,left,body,article,None
5,p0001_r00180_1,1,180,picture,Figure,,None,"[1156.2649808482963, 520.3367996215819, 1192.9...",36.674366,31.546249,1156.938695,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,6,6,True,right,body,article,None
6,p0001_r00015_1,1,15,text,Text,"High rainfall, irrigation and large fertiliser...","High rainfall, irrigation and large fertiliser...","[505.2673591856128, 762.5394285425813, 1400.23...",894.970800,447.058466,400104.272947,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,7,7,True,right,body,article,None
7,p0001_r00016_1,1,16,text,Text,"(Friedl et al., 2016), temperature (Schaufler ...","(Friedl et al., 2016), temperature (Schaufler ...","[766.9031693509583, 1291.0586876419386, 1400.7...",633.896051,175.235603,111081.156859,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,8,8,True,right,body,article,None
8,p0001_r00017_1,1,17,text,Text,The IPCC default emission factor (EF) for N2O ...,The IPCC default emission factor (EF) for N2O ...,"[766.9093481871688, 1474.0980617313853, 1400.7...",633.878619,149.150640,94543.401775,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,9,9,True,right,body,article,None

### Excluded-region inspection

In [12]:
for stage in run.excluded_by_stage:
    print(stage)
    display(stage_exclusions(run, stage).head(100))

label_exclusions

Empty DataFrame
Columns: []
Index: []

page1

,layout_region_id,page_number,docling_reading_order,docling_label,type,text,orig,bbox_px,width_px,height_px,area_px,page_image_path,filter_reason
0,p0001_r00001_1,1,1,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[496.9402939652644, 83.66048737088843, 990.190...",493.250680,29.330683,14467.379375,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
1,p0001_r00002_1,1,2,text,Text,Contents lists available at ScienceDirect,Contents lists available at ScienceDirect,"[571.3508077631892, 158.75491501761027, 929.01...",357.661519,18.284221,6539.562185,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
2,p0001_r00003_1,1,3,section_header,Section-header,"Agriculture, Ecosystems and Environment","Agriculture, Ecosystems and Environment","[421.7419223824623, 218.48031841478922, 1082.9...",661.255028,31.996985,21158.167204,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
3,p0001_r00004_1,1,4,text,Text,journal homepage: www.elsevier.com/locate/agee,journal homepage: www.elsevier.com/locate/agee,"[510.65529015332925, 298.1498347845884, 989.70...",479.048414,16.693684,7997.082611,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
4,p0001_r00005_1,1,5,section_header,Section-header,Exponential response of nitrous oxide (N2O) em...,Exponential response of nitrous oxide (N2O) em...,"[94.01964552272214, 420.2266887679905, 1128.17...",1034.152161,73.956227,76481.992129,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
5,p0001_r00007_1,1,7,footnote,Footnote,"a Centre for Agriculture and the Bioeconomy, Q...","a Centre for Agriculture and the Bioeconomy, Q...","[94.01964552272214, 607.2990210479171, 931.710...",837.690593,18.500003,15497.278700,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_frontmatter
6,p0001_r00008_1,1,8,footnote,Footnote,b Institute for Meteorology and Climate Resear...,b Institute for Meteorology and Climate Resear...,"[94.01964552272214, 628.7070830768455, 1025.05...",931.034678,18.502504,17226.473053,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_frontmatter
7,p0001_r00009_1,1,9,section_header,Section-header,A R T I C L E I N F O,A R T I C L E I N F O,"[94.01964552272214, 714.0980118144686, 315.476...",221.456991,15.998378,3542.952600,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_frontmatter
8,p0001_r00013_1,1,13,footnote,Footnote,* Corresponding author. E-mail address: johann...,* Corresponding author. E-mail address: johann...,"[106.64051111729496, 1682.7284611054156, 566.2...",459.646620,40.417056,18577.563255,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_post_abstract_author_metadata
9,p0001_r00014_1,1,14,section_header,Section-header,A B S T R A C T,A B S T R A C T,"[505.2673591856128, 714.0980118144686, 673.233...",167.965765,15.998378,2687.179756,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_frontmatter
10,p0001_r00018_1,1,18,page_footer,Page-footer,https://doi.org/10.1016/j.agee.2021.107376,https://doi.org/10.1016/j.agee.2021.107376,"[94.01964552272214, 1749.2250029351312, 458.76...",364.748211,16.455592,6002.147842,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_post_abstract_author_metadata
11,p0001_r00019_1,1,19,page_footer,Page-footer,Received 20 October 2020; Received in revised ...,Received 20 October 2020; Received in revised ...,"[94.01964552272214, 1773.0447466755409, 917.09...",823.074281,16.455592,13544.174777,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_post_abstract_author_metadata
12,p0001_r00020_1,1,20,page_footer,Page-footer,Available online 1 March 2021 0167-8809/© 2021...,Available online 1 March 2021 0167-8809/© 2021...,"[93.8460156702328, 1787.427106203544, 511.7930...",417.947013,49.563302,20714.834221,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_post_abstract_author_metadata
13,p0001_r00178_1,1,178,picture,Figure,,None,"[90.41964749889212, 151.82708740234372, 241.64...",151.228491,168.848152,25534.651237,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
14,p0001_r00181_1,1,181,picture,Figure,,None,"[1249.7876917734866, 136.71216964721674, 1396....",147.101084,182.691116,26874.061234,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title
15,p0001_r00182_1,1,182,picture,Figure,,None,"[1250.3246554334623, 368.3581161499025, 1325.7...",75.393639,75.537682,5695.060666,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,page1_upper_before_title

later_headers

,layout_region_id,page_number,docling_reading_order,docling_label,type,text,orig,bbox_px,width_px,height_px,area_px,page_image_path,filter_reason
0,p0002_r00021_1,2,21,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.03057354242945, 84.16870876119484, 1396.47...",1302.444496,26.071718,33956.966017,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header
1,p0003_r00034_1,3,34,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.01964552272214, 84.16870876119484, 1396.47...",1302.455424,26.071718,33957.250929,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header
2,p0004_r00048_1,4,48,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.01964552272214, 84.16870876119484, 1396.47...",1302.455424,26.071718,33957.250929,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header
3,p0005_r00061_1,5,61,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.01964552272214, 84.16870876119484, 1396.47...",1302.455424,26.071718,33957.250929,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header
4,p0006_r00076_1,6,76,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.01964552272214, 84.16870876119484, 1396.47...",1302.455424,26.071718,33957.250929,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header
5,p0007_r00088_1,7,88,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.0329663941113, 84.16870876119484, 1396.475...",1302.442103,26.071718,33956.903631,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header
6,p0008_r00145_1,8,145,page_header,Page-header,"Agriculture, Ecosystems and Environment 313 (2...","Agriculture, Ecosystems and Environment 313 (2...","[94.02856402427668, 84.16870876119484, 1396.47...",1302.446506,26.071718,33957.018408,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,later_page_upper_recurring_header

small_edge_figures

Empty DataFrame
Columns: []
Index: []

nested_assets

Empty DataFrame
Columns: []
Index: []

side_margins

Empty DataFrame
Columns: []
Index: []

footer_furniture

Empty DataFrame
Columns: []
Index: []

document_tail

,layout_region_id,page_number,docling_reading_order,docling_label,type,text,orig,bbox_px,width_px,height_px,area_px,page_image_path,filter_reason
0,p0007_r00091_1,7,91,section_header,Section-header,Appendix A. Supplementary data,Appendix A. Supplementary data,"[94.01964552272214, 374.26591019455884, 421.59...",327.577951,18.284221,5989.507597,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
1,p0007_r00092_1,7,92,text,Text,Supplementary material related to this article...,Supplementary material related to this article...,"[94.01964552272214, 426.5834160380695, 727.839...",633.820294,44.372212,28124.008727,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
2,p0007_r00093_1,7,93,section_header,Section-header,References,References,"[94.01964552272214, 504.990906793597, 202.9504...",108.930823,18.284221,1991.715223,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
3,p0007_r00094_1,7,94,list_item,List,"Albanito, F., Lebender, U., Cornulier, T., Sap...","Albanito, F., Lebender, U., Cornulier, T., Sap...","[94.01964552272214, 553.6078825852255, 721.749...",627.730037,54.467433,34190.843474,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
4,p0007_r00095_1,7,95,list_item,List,"Allen, D.E., Kingston, G., Rennenberg, H., Dal...","Allen, D.E., Kingston, G., Rennenberg, H., Dal...","[94.01964552272214, 613.4395444481155, 706.821...",612.802311,54.469027,33378.745697,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,p0008_r00173_1,8,173,list_item,List,"Wood, S.N., 2011. Fast stable restricted maxim...","Wood, S.N., 2011. Fast stable restricted maxim...","[766.9105497658127, 876.3105980011098, 1394.65...",627.747581,54.467433,34191.799011,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
78,p0008_r00174_1,8,174,list_item,List,"Zhao, X., Nafziger, E.D., Pittelkow, C.M., 201...","Zhao, X., Nafziger, E.D., Pittelkow, C.M., 201...","[766.9105497658127, 936.0019372201126, 1382.03...",615.125996,34.618157,21294.528167,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
79,p0008_r00175_1,8,175,list_item,List,"Zhao, Z., Verburg, K., Huth, N., 2017b. Modell...","Zhao, Z., Verburg, K., Huth, N., 2017b. Modell...","[766.9105497658127, 975.9843232749632, 1394.60...",627.693356,54.469027,34189.846438,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
80,p0008_r00176_1,8,176,list_item,List,"Zhu, Y.G., Li, H., Singh, B.K., Yang, X.R., Ch...","Zhu, Y.G., Li, H., Singh, B.K., Yang, X.R., Ch...","[766.9105497658127, 1035.675662493966, 1394.62...",627.714089,74.462559,46741.197486,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter
81,p0008_r00177_1,8,177,page_footer,Page-footer,8,8,"[740.9230175451427, 1886.8475768046128, 749.90...",8.979105,26.071718,234.100684,/content/drive/MyDrive/00-ENVIRA/01-LayoutPars...,post_conclusion_backmatter

## 9. Post-body assets and final export

In [13]:
display(run.post_body_assets)
display(run.post_body_asset_regions)
manifest = export_pipeline_result(run)
for path in manifest.files:
    print(path)

[]

[]

/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/docling_raw.json
/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/docling_raw.md
/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/page_records.jsonl
/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/docling_regions.jsonl
/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/post_body_assets.jsonl
/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/post_body_asset_regions.jsonl
/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a/summary.csv

## 10. Reproducibility record

In [14]:
print("DOC_ID:", document.doc_id)
print("PDF SHA-256 prefix:", document.pdf_hash)
print("Page range:", document.page_start, document.page_end)
print("Output directory:", document.artifacts.document_dir)
config

DOC_ID: 1-s2.0-S0167880921000803-main__abdb34c0bb6a
PDF SHA-256 prefix: abdb34c0bb6a
Page range: 1 8
Output directory: /content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/outputs/docling_layout_only/1-s2.0-S0167880921000803-main__abdb34c0bb6a

PipelineConfig(runtime=RuntimeConfig(use_google_drive=True, drive_mount_point=PosixPath('/content/drive'), project_dir=PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling'), offline=False, skip_pip_install=False), document=DocumentConfig(source_pdf=PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/1-s2.0-S0167880921000803-main.pdf'), page_start=1, page_end=None, render_dpi=180, run_id='', prefer_persistent_copy=True), docling=DoclingConfig(artifacts_dir=PosixPath('/content/drive/MyDrive/00-ENVIRA/01-LayoutParser/phase1_docling/artifacts/docling_models'), use_local_artifacts=True, require_saved_models=True, auto_download_models=False, force_redownload_models=False, min_model_size_mb=100.0, do_ocr=False, do_table_structure=True, do_formula_enrichment=True, do_code_enrichment=False, code_formula_preset='codeformulav2'), page1=Page1FilterConfig(enabled=True, abstract_aliases=('Abstract', 'Summary'), recover_abstract_heading=True, title_y_min=0.15, title_y_max=0.42, body_anchor_y_max=0.7, lower_metadata_min_y=0.68, hard_footer_y=0.92), headers=HeaderFilterConfig(enabled=True, top_band_ratio=0.14, min_repeat_pages=2), figures=FigureFilterConfig(complete_caption_anchored=True, require_multipanel_hint=True, filter_small_edge_figures=True, header_y1_max=0.12, footer_y0_min=0.9), footer=FooterFilterConfig(enabled=True, compact_enabled=True, min_repeat_pages=2, y0_min=0.88), tail=TailFilterConfig(enabled=True, direct_backmatter_fallback=True), reading_order=ReadingOrderConfig(column_gap_ratio=0.04, min_column_width_ratio=0.2), export=ExportConfig(write_raw=True, write_regions=True, write_overlays=True), exclude_labels=frozenset())